routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'uses'=> 'BlogController@index',
    'as' => 'blog'
]);

Route::get('/blog/about', [
    'uses' => 'BlogController@about',
    'as' => 'blog.about'
]);
Route::get('/blog/contact', [
    'uses' => 'BlogController@contact',
    'as' => 'blog.contact'
]);

Route::get('/app', [
    'uses' => 'ApplicationController@index',
    'as' => 'app'
]);

Route::get('/app/tis', [
    'uses' => 'ApplicationController@tis',
    'as' => 'apps.tis'
]);

Route::get('/app/geoportal',[
    'uses' => 'ApplicationController@geoportal',
    'as' => 'apps.geoportal'
]);

Route::get('/blog/{post}', [
    'uses' => 'BlogController@show',
    'as' => 'blog.show'
]);

Route::get('/category/{category}', [
    'uses' => 'BlogController@category',
    'as' => 'category'
]);

Route::get('/tag/{tag}', [
    'uses' => 'BlogController@tag',
    'as' => 'tag'
]);

Route::auth();

Route::get('/home', 'HomeController@index');

Route::put('/backend/blog/restore/{blog}', [
    'uses' => 'BackendBController@restore',
    'as'   =>  'backend.blog.restore'
]);

Route::delete('/backend/blog/delete/{blog}', [
    'uses' => 'BackendBController@forceDestroy',
    'as'   =>  'backend.blog.delete'
]);


Route::resource('/backend/blog', 'BackendBController', ['as'=> 'backend']);

Route::resource('/backend/categories', 'BackendCController', ['as'=> 'backend']);

Route::resource('/backend/users', 'BackendUController', ['as'=> 'backend']);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use GrahamCampbell\Markdown\Facades\Markdown;

class User extends Authenticatable
{
    use Notifiable;

/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [ 'name', 'email', 'password','bio', 'profile'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];



public function posts()
    {
        return $this->hasMany(Post::class , 'author_id');
    }

    public function getBioHtmlAttribute($value){

    return $this->bio ? Markdown::convertToHtml(e($this->bio)): NULL;
}

public function getProfileUrlAttribute($value){

    $profileUrl = "";

    if ( ! is_null($this->profile))

  {

    $profilePath = public_path(). '/avatar/'.$this->profile;
    if (file_exists($profilePath)) $profileUrl = asset('avatar/'. $this->profile);
  }

  return $profileUrl;
}


public function setPasswordAttribute($value)
{
    if (!empty($value)) $this->attributes['password'] = bcrypt($value);
}




}

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BackendController extends Controller
{
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
}

resources/views/layouts/backend/maincategories.blade.php
<html>
            <head>
                <meta charset="utf-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <title>GEOSPATIAL BHUTAN</title>
                <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
                
                
                
                <link rel="stylesheet" href="/backend/css/bootstrap.min.css">
                <link rel="stylesheet" href="/backend/css/custom.css">
                <link rel="stylesheet" href="/backend/plugins/jasny-bootstrap/css/jasny-bootstrap.min.css">
                <link rel="stylesheet" href="/backend/plugins/font-awesome/css/font-awesome.min.css">
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
                <link rel="stylesheet" href="/backend/css/AdminLTE.css">
                <link rel="stylesheet" href="/backend/plugins/simple-mde/simplemde.min.css">
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
                <link rel="stylesheet" href="/backend/css/skins/_all-skins.min.css">
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-wysiwyg/0.3.3/bootstrap3-wysihtml5.min.css">
                <link rel="stylesheet" href="/backend/plugins/datetimepicker/stylesheets/bootstrap-datetimepicker.css">
                <script data-ad-client="ca-pub-3442421217133965" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

            </head>

<body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">

            @include('layouts.backend.navbar')
            @include('layouts.backend.sidebar')

            @yield('content')

  <footer class="main-footer">
    <strong>Copyright &copy; <a>GEOSPATIAL BHUTAN</a>.</strong>
  </footer>

</div>

<script src="/backend/js/jquery-2.2.3.min.js"></script>
<script src="/backend/plugins/simple-mde/simplemde.min.js"></script>
<script src="/backend/plugins/jasny-bootstrap/js/jasny-bootstrap.min.js"></script>
<script src="/backend/js/bootstrap.min.js"></script>
<script src="/backend/js/app.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment-with-locales.min.js"></script>
<script src="/backend/plugins/datetimepicker/javascripts/bootstrap-datetimepicker.js"></script>


<script type="text/javascript">

$('#title').on('keyup',function ()

{
  var theTitle =this.value.toLowerCase().trim(); 
  
          slugInput =$('#slug'),
  theSlug = theTitle
                    .replace(/&/g,'-and-')
                    .replace(/[^a-z0-9-]+/g,'-')
                    .replace(/\-\-+$/g,'-');
                    

  slugInput.val(theSlug);

});

</script>



<script type="text/javascript">

        $('ul.pagination').addClass('no-margin pagination-sm');
</script>

</body>
</html>

resources/views/layouts/backend/mainposts.blade.php
<html>
            <head>
                <meta charset="utf-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <title>GEOSPATIAL BHUTAN</title>
                <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
                
                
                
                <link rel="stylesheet" href="/backend/css/bootstrap.min.css">
                <link rel="stylesheet" href="/backend/css/custom.css">
                <link rel="stylesheet" href="/backend/plugins/jasny-bootstrap/css/jasny-bootstrap.min.css">
                <link rel="stylesheet" href="/backend/plugins/font-awesome/css/font-awesome.min.css">
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
                <link rel="stylesheet" href="/backend/css/AdminLTE.css">
                <link rel="stylesheet" href="/backend/plugins/simple-mde/simplemde.min.css">
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
                <link rel="stylesheet" href="/backend/css/skins/_all-skins.min.css">
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-wysiwyg/0.3.3/bootstrap3-wysihtml5.min.css">
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker-standalone.css">
                <link rel="stylesheet" href="/backend/plugins/tag-editor/jquery.tageditor.css">
                <script data-ad-client="ca-pub-3442421217133965" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            </head>

<body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">

            @include('layouts.backend.navbar')
            @include('layouts.backend.sidebar')

            @yield('content')

  <footer class="main-footer">
    <strong>Copyright &copy; <a>GEOSPATIAL BHUTAN</a>.</strong>
  </footer>

</div>

<script src="/backend/js/jquery-2.2.3.min.js"></script>
<script src="/backend/plugins/simple-mde/simplemde.min.js"></script>
<script src="/backend/plugins/jasny-bootstrap/js/jasny-bootstrap.min.js"></script>
<script src="/backend/js/bootstrap.min.js"></script>
<script src="/backend/js/app.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment-with-locales.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
<script src="/backend/plugins/tageditor/jquery.caret.min.js"></script>
<script src="/backend/plugins/tageditor/jquery.tag-editor.min.js"></script>





<script type="text/javascript">

$('#title').on('keyup',function ()

{
  var theTitle =this.value.toLowerCase().trim(); 
  
          slugInput =$('#slug'),
  theSlug = theTitle
                    .replace(/&/g,'-and-')
                    .replace(/[^a-z0-9-]+/g,'-')
                    .replace(/\-\-+$/g,'-');
                    

  slugInput.val(theSlug);

});

</script>

<script type="text/javascript">

var simplemde1 = new SimpleMDE({ element: $("#body" )[0] });
var simplemde2 = new SimpleMDE({ element: $("#excerpt")[0] });

</script>

<script type="text/javascript">

        $('ul.pagination').addClass('no-margin pagination-sm');
</script>


<script  type="text/javascript">

 $('#published_at').datetimepicker({

  format: 'YYYY-MM-DD HH:mm:ss',
  
 });

</script>


<script  type="text/javascript">

 $('#draft').click(function(e){
  e.preventDefault();
  $('#published_at').val('');
  $('#post-form').submit();


 });

</script>

</body>
</html>

resources/views/layouts/backend/mainusers.blade.php
<html>
            <head>
                <meta charset="utf-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <title>GEOSPATIAL BHUTAN</title>
                <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
                
                
                
                <link rel="stylesheet" href="/backend/css/bootstrap.min.css">
                <link rel="stylesheet" href="/backend/css/custom.css">
                <link rel="stylesheet" href="/backend/plugins/jasny-bootstrap/css/jasny-bootstrap.min.css">
                <link rel="stylesheet" href="/backend/plugins/font-awesome/css/font-awesome.min.css">
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
                <link rel="stylesheet" href="/backend/css/AdminLTE.css">
                <link rel="stylesheet" href="/backend/plugins/simple-mde/simplemde.min.css">
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
                <link rel="stylesheet" href="/backend/css/skins/_all-skins.min.css">
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-wysiwyg/0.3.3/bootstrap3-wysihtml5.min.css">
                <link rel="stylesheet" href="/backend/plugins/datetimepicker/stylesheets/bootstrap-datetimepicker.css">
                <script data-ad-client="ca-pub-3442421217133965" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

            </head>

<body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">

            @include('layouts.backend.navbar')
            @include('layouts.backend.sidebar')

            @yield('content')

  <footer class="main-footer">
    <strong>Copyright &copy; <a>GEOSPATIAL BHUTAN</a>.</strong>
  </footer>

</div>

<script src="/backend/js/jquery-2.2.3.min.js"></script>
<script src="/backend/plugins/simple-mde/simplemde.min.js"></script>
<script src="/backend/plugins/jasny-bootstrap/js/jasny-bootstrap.min.js"></script>
<script src="/backend/js/bootstrap.min.js"></script>
<script src="/backend/js/app.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment-with-locales.min.js"></script>
<script src="/backend/plugins/datetimepicker/javascripts/bootstrap-datetimepicker.js"></script>




<script type="text/javascript">

var simplemde1 = new SimpleMDE({ element: $("#bio" )[0] });


</script>

<script type="text/javascript">

        $('ul.pagination').addClass('no-margin pagination-sm');
</script>


</body>
</html>

resources/views/layouts/backend/navbar.blade.php
<header class="main-header">

<a href="/" class="logo">

<span class="logo-mini"><b>GEOSPATIAL</b> BHUTAN</span>

<span class="logo-lg"><b>GEOSPATIAL</b> BHUTAN</span>
</a>
<nav class="navbar navbar-static-top">

<div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
    <li class="dropdown user user-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <img src="{{Auth:: user()->profile_url}}" class="user-image" alt="{{ Auth:: user()-> name}}">
        <span class="hidden-xs">{{ Auth:: user()->name}}</span>
        </a>
        <ul class="dropdown-menu">
    
        <li class="user-header">
        <img src="{{Auth:: user()->profile_url}}" class="user-image" alt="{{ Auth:: user()-> name}}">
            <p>{{ Auth:: user()->name}}

            <small> Member Since {{ Auth:: user()-> created_at}}</small>
            </p>
           
        </li>
    
        <li class="user-footer">
            <div class="pull-left">
            <a class="btn btn-default btn-flat"
             href = "{{url('/logout')}}"
             onclick = "event.preventDefault();
             document.getElementById('logout-form').submit();">Logout </a>             
             
             
             <form id="logout-form" method='POST' action="{{ url('/logout') }}"  style="display:none">
             {{ csrf_field() }}
            
            </form>
            </div>
        </li>
        </ul>
    </li>
    </ul>
</div>
</nav>
</header>

resources/views/layouts/backend/sidebar.blade.php
<aside class="main-sidebar">

    <section class="sidebar">
    
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{Auth:: user()->profile_url}}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ Auth:: user()-> name}}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <ul class="sidebar-menu">
        <li>
          <a href="{{url('/home')}}">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
          </a>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-pencil"></i>
            <span>Blog</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ route('backend.blog.index') }} "><i class="fa fa-circle-o"></i> All Posts</a></li>
            <li><a href="{{ route('backend.blog.create')}} "><i class="fa fa-circle-o"></i> Add New</a></li>
          </ul>
        </li>
        <li><a href="{{ route('backend.categories.index')}}"><i class="fa fa-folder"></i> <span>Categories</span></a></li>
        <li><a href="{{ route('backend.users.index')}}"><i class="fa fa-users"></i> <span>Users</span></a></li>
      </ul>
    </section>
  
  </aside>