routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'uses'=> 'BlogController@index',
    'as' => 'blog'
]);

Route::get('/blog/about', [
    'uses' => 'BlogController@about',
    'as' => 'blog.about'
]);
Route::get('/blog/contact', [
    'uses' => 'BlogController@contact',
    'as' => 'blog.contact'
]);

Route::get('/app', [
    'uses' => 'ApplicationController@index',
    'as' => 'app'
]);

Route::get('/app/tis', [
    'uses' => 'ApplicationController@tis',
    'as' => 'apps.tis'
]);

Route::get('/app/geoportal',[
    'uses' => 'ApplicationController@geoportal',
    'as' => 'apps.geoportal'
]);

Route::get('/blog/{post}', [
    'uses' => 'BlogController@show',
    'as' => 'blog.show'
]);

Route::get('/category/{category}', [
    'uses' => 'BlogController@category',
    'as' => 'category'
]);

Route::get('/tag/{tag}', [
    'uses' => 'BlogController@tag',
    'as' => 'tag'
]);

Route::auth();

Route::get('/home', 'HomeController@index');

Route::put('/backend/blog/restore/{blog}', [
    'uses' => 'BackendBController@restore',
    'as'   =>  'backend.blog.restore'
]);

Route::delete('/backend/blog/delete/{blog}', [
    'uses' => 'BackendBController@forceDestroy',
    'as'   =>  'backend.blog.delete'
]);


Route::resource('/backend/blog', 'BackendBController', ['as'=> 'backend']);

Route::resource('/backend/categories', 'BackendCController', ['as'=> 'backend']);

Route::resource('/backend/users', 'BackendUController', ['as'=> 'backend']);

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use GrahamCampbell\Markdown\Facades\Markdown;
use App\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Category;
use App\Tag;


class Post extends Model
{

            use SoftDeletes;
            protected $dates = ['published_at'];
            protected $fillable =[ 'view_count','image','author_id','title', 'category_id', 'slug', 'body', 'excerpt', 'published_at'];

        public function category(){

            return $this->belongsTo(Category::class);
        }


        public function author()
        {
            return $this->belongsTo(User::class);
        }


        public function dateFormatted($showTimes = false)
        {
            $format = "d/m/Y";
            if ($showTimes) $format = $format . " H:i:s";
            return $this->created_at->format($format);

        }

        public function PublicationLabel()
        {

        if ( ! $this->published_at ) {

            return '<span class="label label-warning">Draft</span>';
        } 

        elseif ($this->published_at && $this->published_at->isFuture() )
        {
            return '<span class="label label-info"> Schedule</span>';
        }
        elseif($this-> published_at && $this->deleted_at) {

            return '<span class="label label-info">Deleted</span>';
        }
        else {

            return '<span class="label label-success">Published</span>';
        }

        }


        public function getBodyHtmlAttribute($value){

            return $this->body ? Markdown::convertToHtml(e($this->body)): NULL;
        }


        public function getExcerptHtmlAttribute($value){

            return $this->excerpt ? Markdown::convertToHtml(e($this->excerpt)):NULL;
        }


        public function getImageUrlAttribute($value){

            $imageUrl = "";

            if ( ! is_null($this->image))

        {

            $imagePath = public_path(). '/img/'.$this->image;
            if (file_exists($imagePath)) $imageUrl = asset('img/'. $this->image);
        }

        return $imageUrl;
        }

        public function getDateAttribute($value)

        {
            return is_null($this->published_at) ? '' : $this->published_at->diffForHumans();
        }


        public function scopeLatestFirst()

        {
            return $this->orderBy('created_at', 'desc');
        }


        public function scopePopular()

        {
            return $this->orderBy('view_count', 'desc');
        }


        public function scopePublished($query)

        {
            return $query->where("published_at", "<=", Carbon::now());
        }

        public function scopeScheduled($query)

        {
            return $query->where("published_at", ">", Carbon::now());
        }

        public function scopeDraft($query)

        {
            return $query->whereNull("published_at");
        }


        public function setPublishedAtAttribute($value)
        {
            $this->attributes['published_at'] = $value ?: NULL;
        }

        public function scopeFilter($query, $term)

        {
            if ($term){

                $query->where(function($q) use ($term){


                    $q->whereHas('author', function($qa) use ($term){

                        $qa->Where('name', 'LIKE', "%{$term}%");
                    });


                    $q->orWhereHas('category', function($qc) use ($term){

                        $qc->orWhere('title', 'LIKE', "%{$term}%");
                    });
                    
                $q->orWhere('title', 'LIKE', "%{$term}%");
                $q->orWhere('excerpt', 'LIKE', "%{$term}%");


                });

            }
        }

        public function tags(){

            return $this->belongsToMany(Tag::class);
        }


        public function createTags($str)
        {
            $tags = explode(",", $str);
            $tagIds = [];
    
            foreach ($tags as $tag)
            {
                $newTag = Tag::firstOrCreate([
                    'name' => ucwords(trim($tag))
                ]);
    
                $tagIds[] = $newTag->id;
            }
    
            $this->tags()->sync($tagIds);
        }

        public function getTagsHtmlAttribute()
        {
            $anchors = [];
            foreach($this->tags as $tag) {
                $anchors[] = '<a href="' . route('tag', $tag->name) . '">' . '</a>';
            }
            return implode(", ", $anchors);
        }


}

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BackendController extends Controller
{
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;
use App\Category;
use App\Post;
use App\User;
use App\Tag;

class BlogController extends Controller
{

    protected $limit = 2;
    public function index()
    {
        $categories = Category::with('posts')->orderBy('title', 'asc')->get();

        $posts = Post::with('author')
                    ->latestFirst()
                    ->published()
                    ->filter(request('term'))
                     ->simplePaginate($this->limit);

        return view("blog.index", compact('posts', 'categories'));
    }

    public function about()
    {
        return view("blog.about.about");
    }

    public function contact()
    {
        return view("blog.contact.contact");
    }

    public function category($id)
    {
        $categories = Category::with('posts')->orderBy('title', 'asc')->get();

        $posts = Post::with('author')
                    ->latestFirst()
                    ->where('category_id', $id)
                    ->simplePaginate($this->limit);

         return view("blog.index", compact('posts'));

    }

    public function tag(Tag $id)
    {
        $tag = Post::with('tags')->orderBy('title', 'asc')->get();

        $posts = Post::with('author')
                    ->latestFirst()
                    ->published()
                    ->simplePaginate($this->limit);

         return view("blog.index", compact('posts'));

    }

    public function show(Post $post)

    {


        // upadte post with view count

        $post->increment('view_count');
        
        return view('blog.show', compact('post'));
    }

        
}

resources/views/backend/blog/create.blade.php
@extends('layouts.backend.mainposts')


@section('title', 'GEOSPATIAL BHUTAN')

@section('content')

<div class="content-wrapper">
    
    <section class="content-header">
      <h1>Add New Post</h1>
      <ol class="breadcrumb">
        <li>
            <a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i>Dashboard </a>
             <a href="{{ route('backend.blog.index')}}"><li>Blog</li></a>
            <li class="active">Add New</li>

        </li>
      </ol>
    </section>

<section class="content">
    <div class="row">

    {!! Form::model($post, [
                            
        'method' =>'POST',
        'route'  => 'backend.blog.store',
        'files'  => TRUE,
        'id' =>'post-form'

    ]) !!}
           @include('backend.blog.form')

            <hr>

                            {!! Form::close() !!}
                        
        </div>

        

     
     
    </section>
   
  </div>
@endsection

resources/views/backend/blog/edit.blade.php
@extends('layouts.backend.mainposts')


@section('title', 'GEOSPATIAL BHUTAN')

@section('content')

<div class="content-wrapper">
    
    <section class="content-header">
      <h1>Edit Post</h1>
      <ol class="breadcrumb">
        <li>
            <a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i>Dashboard </a>
             <a href="{{ route('backend.blog.index')}}"><li>Blog</li></a>
            <li class="active">Edit Post</li>

        </li>
      </ol>
    </section>

<section class="content">
    <div class="row">

    {!! Form::model($post, [
                            
        'method' =>'PUT',
        'route'  => ['backend.blog.update', $post->id],
        'files'  => TRUE,
        'id' =>'post-form'

    ]) !!}
           @include('backend.blog.form')

            <hr>

                            {!! Form::close() !!}
                        
        </div>

        

     
     
    </section>
   
  </div>
@endsection

resources/views/backend/blog/form.blade.php
<div class="col-xs-9">
                    <div class="box">
                            <div class="box-body ">

                            <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">

                                    {!! Form::label('title') !!}
                                    {!! Form::text('title',null, ['class = "form-control"']) !!}
                            
                                    @if ($errors->has('title'))

                                        <span class='help-block'> {{ $errors -> first('title')}}
                                    @endif
                            </div>

                            <div class="form-group-excerpt {{ $errors->has('excerpt') ? 'has-error' : '' }}">

                                    {!! Form::label('excerpt') !!}
                                    {!! Form::textarea('excerpt',null, ['class' => "form-control"]) !!}
                            
                                    @if ($errors->has('excerpt'))

                                        <span class='help-block'> {{ $errors -> first('excerpt')}}
                                    @endif
                            </div>

                            <div class="form-group-body {{ $errors->has('body') ? 'has-error' : '' }}">

                                    {!! Form::label('body') !!}
                                    {!! Form::textarea('body',null, ['class' => "form-control"]) !!}
                            
                                    @if ($errors->has('body'))
                                        <span class='help-block'> {{ $errors -> first('body')}}
                                    @endif
                            </div>
                    </div>
                    
            
            </div>
        </div>

            <div class="col-xs-3">
                <div class="box with-broder">
                        <div class="box-body"> 
                            <div class="form-group {{ $errors->has('slug') ? 'has-error' : '' }}">

                                    {!! Form::label('slug') !!}
                                    {!! Form::text('slug',null, ['class' => "form-control"]) !!}

                                    @if ($errors->has('slug'))

                                        <span class='help-block'> {{ $errors -> first('slug')}}
                                    @endif

                            </div>    
                        </div>

                        <div class="box-body">  
                            <div class="form-group {{ $errors->has('category_id') ? 'has-error' : '' }}">

                                {!! Form::label('category_id', 'Category') !!}
                                {!! Form::select('category_id',App\Category::pluck('title', 'id'), null , ['class' => "form-control", 'placeholder' => "Choose Category"]) !!}

                                @if ($errors->has('category_id'))

                                    <span class='help-block'> {{ $errors -> first('category_id')}}
                                @endif

                            </div> 
                        </div>

                        <div class="box-body">
                            <div class="form-group {{ $errors->has('author_id') ? 'has-error' : '' }}">

                                {!! Form::label('author_id', 'Author') !!}
                                {!! Form::select('author_id',App\User::pluck('name', 'id'), null , ['class' => "form-control", 'placeholder' => "Choose Author"]) !!}

                                @if ($errors->has('author_id'))

                                    <span class='help-block'> {{ $errors -> first('author_id')}}
                                @endif

                            </div> 
                        </div>

                   
                        <div class="box-body">

                            <div class="form-group {{ $errors->has('published_at') ? 'has-error' : '' }}">

                                {!! Form::label('post_tags', 'Tags') !!}
                                {!! Form::text('post_tags', null, ['class' => "form-control"]) !!}

                            </div>

                           
                        </div>
                    
                        <div class="box-body">
                            <div class="form-group {{ $errors->has('published_at') ? 'has-error' : '' }}">

                                {!! Form::label('published_at', 'Published Date') !!}
                                {!! Form::text('published_at', null, ['class' => "form-control", 'placeholder' => 'Y-m-d H:i:s']) !!}

                                @if ($errors->has('published_at'))
                                    <span class='help-block'> {{ $errors -> first('published_at')}}
                                @endif

                            </div>
                        </div>

                        <div class="box-body">
                                <div class="form-group {{ $errors->has('image') ? 'has-error' : '' }}">

                                            {!! Form::label('image', 'Post Image') !!}

                                            <div class="fileinput fileinput-new text-center"  data-provides="fileinput">
                                                    <div class="fileinput-new img-thumbnail" style="width:220px; height: 230px;">
                                                        <img src="{{ ($post->image_url) ? $post->image_url: ' https://place-hold.it/210x220/666/fff/000.gif' }}"  alt="...">
                                                    </div>
                                                    <div class="fileinput-preview fileinput-exists img-thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                                                    <div class=btn>
                                                        <span class="btn btn-primary btn-file"><span class="fileinput-new">Select Image</span><span class="fileinput-exists">Change</span> {!! Form::file('image') !!}</span>
                                                        <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                                                    </div>
                                            </div>

                                            @if ($errors->has('image', null))
                                                <span class='help-block'> {{ $errors -> first('image')}}
                                            @endif

                                </div>
                        </div>

                        <div class="box-footer">
                            <div class="pull-left">
                                <a id="draft" class="btn btn-primary">Save Draft</a>

                            </div>
                            <div class="pull-right">
                            {!! Form::Submit('Publish', ['class' => "btn btn-primary"]) !!}
                                
                            </div>
                        </div>

                    </div>
                </div>

            </div>

resources/views/backend/blog/index.blade.php
@extends('layouts.backend.mainposts')


@section('title', 'GEOSPATIAL BHUTAN')

@section('content')

<div class="content-wrapper">
    
    <section class="content-header">
      <h1> Display All Blog Posts</h1>
      <ol class="breadcrumb">
        <li>
            <a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i>Dashboard </a>
            <li href=" {{ route('backend.blog.index') }}"> Blog</li>
            <li class="active">All Posts</li>



        </li>
      </ol>
    </section>


    <section class="content">
        <div class="row">
          <div class="col-xs-12">
            <div class="box">

            <div class="box-header clearfix">
                <div class="pull-left">
                
                    <a href="{{ route('backend.blog.create')}}" class="btn btn-success"><i class="fa fa-plus"></i> Add New</a>                
                
                </div>

                <div class="pull-right" style="padding: 7px 0;">
                
                    <a href="?status=all">All</a> |
                    <a href="?status=published">Published</a> |
                    <a href="?status=scheduled">Scheduled</a> |
                    <a href="?status=draft">Draft</a> |
                    <a href="?status=trash">Trash</a>                 
                
                </div>

            </div>

            <div class="box-header " style="padding: 5px 0;">
            
            @if(session('message'))

                <div class="alert alert-success">
                    {{session ('message')}}
                </div>

                @elseif(session('trash-message'))

                <?php list($message, $postId) = session ('trash-message') ?>         

                  {!! Form::open(['method' => 'PUT', 'route' =>['backend.blog.restore', $postId]]) !!}

                    <div class="alert alert-info">
                                    {{ $message }}
                        <button type="submit" class="btn btn-sm btn-warning"><i class="fa fa-undo"></i> Undo </button>

                                {!! Form::close() !!}

                    </div>

            @endif
        

            </div>
           
              <div class="box-body ">

                @if($onlyTrashed)

                        @include('backend.blog.table-trash')
                @else

                        @include('backend.blog.table')
                @endif


            
            </div>

        <div class="box-footer clearfix">
            <div class="pull-left">
                   
                    {{ $posts->appends(Request::query())->links()}}
            </div>

            <div class="pull-right">
                <strong> {{ $posts->count()}} Items </strong>
            </div>
        </div>

        
           
            </div>
          
          </div>
        </div>
     
    </section>
   
  </div>
@endsection

resources/views/backend/blog/table-trash.blade.php
<table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td >Action</td>
                        <td>Title</td>
                        <td width="120">Author</td>
                        <td width="150">Category</td>
                        <td width="150">Date</td>
                    </tr>
                </thead>


                <tbody>

                @foreach( $posts as $post)
                   <tr>
                       <td>
                                {!! Form::open(['style' => 'display: inline-block', 'method' => 'PUT', 'route' =>['backend.blog.restore',$post->id]])!!}

                           <button title="Restore" onclick="return confirm('Are you sure you want to restore this post ?')" class="btn btn-xs btn-default">
                                        <i class="fa fa-undo"></i>
                                       
                           </button>   
                                {!! Form::close() !!}

                            {!! Form::open(['style' => 'display:inline-block' ,'method' => 'DELETE', 'route' =>['backend.blog.delete',$post->id]])!!}

                            <button title="Delete Permanent" onclick="return confirm('Are you sure you want to delete this post permanently ?')" type="submit" class="btn btn-xs btn-danger">
                                        <i class="fa fa-times"></i>

                            </button>

                                {!! Form::close() !!}

                       </td>
                      
                       <td> {{$post->title}}</td>
                       <td>{{$post->author->name}}</td>
                       <td>{{$post->category-> title}}</td>
                       <td>
                           <abbr title="{{$post->dateFormatted(true)}}">{{$post->dateFormatted()}}</abbr>
                            {!! $post-> publicationLabel() !!}
                       </td>
                   </tr>

                   @endforeach
                </tbody>
</table>

resources/views/backend/blog/table.blade.php
<table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td width="80">Action</td>
                        <td>Title</td>
                        <td width="120">Author</td>
                        <td width="150">Category</td>
                        <td width="150">Date</td>
                    </tr>
                </thead>


                <tbody>

                @foreach( $posts as $post)
                   <tr>
                       <td>
                                {!! Form::open(['method' => 'DELETE', 'route' =>['backend.blog.destroy',$post->id]])!!}

                           <a href="{{ route('backend.blog.edit', $post->id)}}" class="btn btn-xs btn-default">
                                        <i class="fa fa-pencil-square-o"></i>
                            </a>


                            <button type="submit" onclick="return confirm('Are you sure you want to move this post to trash ?')" class="btn btn-xs btn-danger">
                                        <i class="fa fa-trash-o"></i>

                            </button>

                                {!! Form::close() !!}

                       </td>
                      
                       <td> {{$post->title}}</td>
                       <td>{{$post->author->name}}</td>
                       <td>{{$post->category-> title}}</td>
                       <td>
                           <abbr title="{{$post->dateFormatted(true)}}">{{$post->dateFormatted()}}</abbr>
                            {!! $post-> publicationLabel() !!}
                       </td>
                   </tr>

                   @endforeach
                </tbody>
</table>