routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'uses'=> 'BlogController@index',
    'as' => 'blog'
]);

Route::get('/blog/about', [
    'uses' => 'BlogController@about',
    'as' => 'blog.about'
]);
Route::get('/blog/contact', [
    'uses' => 'BlogController@contact',
    'as' => 'blog.contact'
]);

Route::get('/app', [
    'uses' => 'ApplicationController@index',
    'as' => 'app'
]);

Route::get('/app/tis', [
    'uses' => 'ApplicationController@tis',
    'as' => 'apps.tis'
]);

Route::get('/app/geoportal',[
    'uses' => 'ApplicationController@geoportal',
    'as' => 'apps.geoportal'
]);

Route::get('/blog/{post}', [
    'uses' => 'BlogController@show',
    'as' => 'blog.show'
]);

Route::get('/category/{category}', [
    'uses' => 'BlogController@category',
    'as' => 'category'
]);

Route::get('/tag/{tag}', [
    'uses' => 'BlogController@tag',
    'as' => 'tag'
]);

Route::auth();

Route::get('/home', 'HomeController@index');

Route::put('/backend/blog/restore/{blog}', [
    'uses' => 'BackendBController@restore',
    'as'   =>  'backend.blog.restore'
]);

Route::delete('/backend/blog/delete/{blog}', [
    'uses' => 'BackendBController@forceDestroy',
    'as'   =>  'backend.blog.delete'
]);


Route::resource('/backend/blog', 'BackendBController', ['as'=> 'backend']);

Route::resource('/backend/categories', 'BackendCController', ['as'=> 'backend']);

Route::resource('/backend/users', 'BackendUController', ['as'=> 'backend']);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use GrahamCampbell\Markdown\Facades\Markdown;

class User extends Authenticatable
{
    use Notifiable;

/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [ 'name', 'email', 'password','bio', 'profile'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];



public function posts()
    {
        return $this->hasMany(Post::class , 'author_id');
    }

    public function getBioHtmlAttribute($value){

    return $this->bio ? Markdown::convertToHtml(e($this->bio)): NULL;
}

public function getProfileUrlAttribute($value){

    $profileUrl = "";

    if ( ! is_null($this->profile))

  {

    $profilePath = public_path(). '/avatar/'.$this->profile;
    if (file_exists($profilePath)) $profileUrl = asset('avatar/'. $this->profile);
  }

  return $profileUrl;
}


public function setPasswordAttribute($value)
{
    if (!empty($value)) $this->attributes['password'] = bcrypt($value);
}




}

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BackendController extends Controller
{
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
}

resources/views/backend/users/create.blade.php
@extends('layouts.backend.mainusers')


@section('title', 'GEOSPATIAL BHUTAN')

@section('content')

<div class="content-wrapper">
    
    <section class="content-header">
      <h1>Add New User</h1>
      <ol class="breadcrumb">
        <li>
            <a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i>Dashboard </a>
             <a href="{{ route('backend.users.index')}}"><li>Users</li></a>
            <li class="active">Add New</li>

        </li>
      </ol>
    </section>

<section class="content">
    <div class="row">

                            {!! Form::model($user, [
                                                    
                                'method' =>'POST',
                                'route'  => 'backend.users.store',
                                'files'  => TRUE,
                                'id' =>'user-form'

                            ]) !!}
           @include('backend.users.form')

            <hr>

                            {!! Form::close() !!}
                        
        </div>

        

     
     
    </section>
   
  </div>
@endsection

resources/views/backend/users/edit.blade.php
@extends('layouts.backend.mainusers')


@section('title', 'GEOSPATIAL BHUTAN')

@section('content')

<div class="content-wrapper">
    
    <section class="content-header">
      <h1>Edit User</h1>
      <ol class="breadcrumb">
        <li>
            <a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i>Dashboard </a>
             <a href="{{ route('backend.blog.index')}}"><li>Users</li></a>
            <li class="active">Edit User</li>

        </li>
      </ol>
    </section>

<section class="content">
    <div class="row">

    {!! Form::model($user, [
                            
        'method' =>'PUT',
        'route'  => ['backend.users.update', $user->id],
        'files'  => TRUE,
        'id' =>'user-form'

    ]) !!}
           @include('backend.users.form')

            <hr>

                            {!! Form::close() !!}
                        
        </div>

        

     
     
    </section>
   
  </div>
@endsection

resources/views/backend/users/form.blade.php
<div class="col-xs-9">
                    <div class="box with-broder">
                        <div class="box-body ">

                            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">

                                    {!! Form::label('name') !!}
                                    {!! Form::text('name',null, ['class = "form-control"']) !!}
                            
                                    @if ($errors->has('name'))

                                        <span class='help-block'> {{ $errors -> first('name')}}
                                    @endif
                            </div>

                            <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">

                                    {!! Form::label('email') !!}
                                    {!! Form::text('email',null, ['class' => "form-control"]) !!}

                                    @if ($errors->has('email'))

                                        <span class='help-block'> {{ $errors -> first('email')}}
                                    @endif

                            </div> 

                            <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">

                                    {!! Form::label('password') !!}
                                    {!! Form::password('password', ['class' => "form-control"]) !!}

                                    @if ($errors->has('password'))

                                        <span class='help-block'> {{ $errors -> first('password')}}
                                    @endif

                            </div>  

                            <div class="form-group-bio {{ $errors->has('bio') ? 'has-error' : '' }}">

                                    {!! Form::label('bio') !!}
                                    {!! Form::textarea ('bio', null, ['class' => "form-control"]) !!}

                                    @if ($errors->has('bio'))
                                    <span class='help-block'> {{ $errors -> first('bio')}}
                                    @endif

                            </div>  

                            


 
                        </div>
                    
            
                    </div>
</div>

            <div class="col-xs-3">
                <div class="box with-broder">
                        <div class="box-body">
                                <div class="form-group {{ $errors->has('profile') ? 'has-error' : '' }}">

                                            {!! Form::label('profile', 'Profile') !!}

                                            <div class="fileinput fileinput-new text-center"  data-provides="fileinput">
                                                    <div class="fileinput-new img-thumbnail" style="width:220px; height: 230px;">
                                                        <img src="($post->profile_url) ? $post->profile_url: ' https://place-hold.it/210x220/666/fff/000.gif' "  alt="...">
                                                    </div>
                                                    <div class="fileinput-preview fileinput-exists img-thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                                                    <div class=btn>
                                                        <span class="btn btn-primary btn-file"><span class="fileinput-new">Select Profile</span><span class="fileinput-exists">Change</span> {!! Form::file('profile') !!}</span>
                                                        <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                                                    </div>
                                            </div>

                                            @if ($errors->has('profile', null))
                                                <span class='help-block'> {{ $errors -> first('profile')}}
                                            @endif

                                </div>
                        </div>

                        <div class="box-footer clearfix">

                            <div class="pull-left">
                            <button type="submit" class="btn btn-primary">{{ $user -> exists ? 'Update':'Save'}}</button>
                            </div>

                            <div class="pull-right">
                            
                            <a href="{{ route('backend.users.index') }}" class="btn btn-primary">Cancel</a>
                            </div>
                            
                            
                        </div>

                    </div>
                </div>

            </div>

resources/views/backend/users/index.blade.php
@extends('layouts.backend.mainusers')


@section('title', 'GEOSPATIAL BHUTAN')

@section('content')

<div class="content-wrapper">
    
    <section class="content-header">
      <h1> Display All Users</h1>
      <ol class="breadcrumb">
        <li>
            <a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i>Dashboard </a>
            <li href=" {{ route('backend.users.index') }}">Users</li>
            <li class="active">All Users</li>



        </li>
      </ol>
    </section>


    <section class="content">
        <div class="row">
          <div class="col-xs-12">
            <div class="box">

            <div class="box-header clearfix">
                <div class="pull-left">
                
                    <a href="{{ route('backend.users.create')}}" class="btn btn-success"><i class="fa fa-plus"></i> Add New</a>                
                
                </div>

                <div class="pull-right">
                
                                     
                
                </div>

            </div>

            <div class="box-header " style="padding: 5px 0;">
            
            @if(session('message'))

                <div class="alert alert-success">
                    {{session ('message')}}
                </div>


            @elseif(session('error-message'))

                <div class="alert alert-danger">
                    {{session ('error-message')}}
                </div>
            
            @endif
        

            </div>
           
              <div class="box-body ">

               

                        @include('backend.users.table')
               

            
            </div>

        <div class="box-footer clearfix">
            <div class="pull-left">
                   
                    {{ $users->links()}}
            </div>

            <div class="pull-right">
                <strong> {{ $users-> count()}} Users </strong>
            </div>
        </div>

        
           
            </div>
          
          </div>
        </div>
     
    </section>
   
  </div>
@endsection

resources/views/backend/users/table.blade.php
<table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td width="80">Action</td>
                        <td>Name</td>
                        <td >Email</td>
                        <td >Bio</td>
                        <td width="80">Post Count</td>
                    </tr>
                </thead>


                <tbody>

                @foreach( $users as $user)
                   <tr>
                       <td>
                                {!! Form::open(['method' => 'DELETE', 'route' =>['backend.users.destroy',$user->id]])!!}

                           <a href="{{ route('backend.users.edit', $user->id)}}" class="btn btn-xs btn-default">
                                        <i class="fa fa-pencil-square-o"></i>
                            </a>

                            @if($user->id == config('cms.default_user_id'))

                            <button type="submit" onclick="return confirm('You are not allowed to delete this user !')" class="btn btn-xs btn-danger">
                                        <i class="fa fa-times"></i>
                            @else

                            <button type="submit" onclick="return confirm('Are you sure you want to delete the users ?')" class="btn btn-xs btn-danger">
                                        <i class="fa fa-times"></i>

                            </button>

                            @endif

                                {!! Form::close() !!}

                       </td>
                      
                       <td> {{$user->name}}</td>
                       <td> {{$user->email}}</td>
                       <td> {{$user->bio}}</td>
                       <td>{{$user ->posts->count()}}</td>
                   </tr>

                   @endforeach
                </tbody>
</table>