routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'uses'=> 'BlogController@index',
    'as' => 'blog'
]);

Route::get('/blog/about', [
    'uses' => 'BlogController@about',
    'as' => 'blog.about'
]);
Route::get('/blog/contact', [
    'uses' => 'BlogController@contact',
    'as' => 'blog.contact'
]);

Route::get('/app', [
    'uses' => 'ApplicationController@index',
    'as' => 'app'
]);

Route::get('/app/tis', [
    'uses' => 'ApplicationController@tis',
    'as' => 'apps.tis'
]);

Route::get('/app/geoportal',[
    'uses' => 'ApplicationController@geoportal',
    'as' => 'apps.geoportal'
]);

Route::get('/blog/{post}', [
    'uses' => 'BlogController@show',
    'as' => 'blog.show'
]);

Route::get('/category/{category}', [
    'uses' => 'BlogController@category',
    'as' => 'category'
]);

Route::get('/tag/{tag}', [
    'uses' => 'BlogController@tag',
    'as' => 'tag'
]);

Route::auth();

Route::get('/home', 'HomeController@index');

Route::put('/backend/blog/restore/{blog}', [
    'uses' => 'BackendBController@restore',
    'as'   =>  'backend.blog.restore'
]);

Route::delete('/backend/blog/delete/{blog}', [
    'uses' => 'BackendBController@forceDestroy',
    'as'   =>  'backend.blog.delete'
]);


Route::resource('/backend/blog', 'BackendBController', ['as'=> 'backend']);

Route::resource('/backend/categories', 'BackendCController', ['as'=> 'backend']);

Route::resource('/backend/users', 'BackendUController', ['as'=> 'backend']);

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use GrahamCampbell\Markdown\Facades\Markdown;
use App\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Category;
use App\Tag;


class Post extends Model
{

            use SoftDeletes;
            protected $dates = ['published_at'];
            protected $fillable =[ 'view_count','image','author_id','title', 'category_id', 'slug', 'body', 'excerpt', 'published_at'];

        public function category(){

            return $this->belongsTo(Category::class);
        }


        public function author()
        {
            return $this->belongsTo(User::class);
        }


        public function dateFormatted($showTimes = false)
        {
            $format = "d/m/Y";
            if ($showTimes) $format = $format . " H:i:s";
            return $this->created_at->format($format);

        }

        public function PublicationLabel()
        {

        if ( ! $this->published_at ) {

            return '<span class="label label-warning">Draft</span>';
        } 

        elseif ($this->published_at && $this->published_at->isFuture() )
        {
            return '<span class="label label-info"> Schedule</span>';
        }
        elseif($this-> published_at && $this->deleted_at) {

            return '<span class="label label-info">Deleted</span>';
        }
        else {

            return '<span class="label label-success">Published</span>';
        }

        }


        public function getBodyHtmlAttribute($value){

            return $this->body ? Markdown::convertToHtml(e($this->body)): NULL;
        }


        public function getExcerptHtmlAttribute($value){

            return $this->excerpt ? Markdown::convertToHtml(e($this->excerpt)):NULL;
        }


        public function getImageUrlAttribute($value){

            $imageUrl = "";

            if ( ! is_null($this->image))

        {

            $imagePath = public_path(). '/img/'.$this->image;
            if (file_exists($imagePath)) $imageUrl = asset('img/'. $this->image);
        }

        return $imageUrl;
        }

        public function getDateAttribute($value)

        {
            return is_null($this->published_at) ? '' : $this->published_at->diffForHumans();
        }


        public function scopeLatestFirst()

        {
            return $this->orderBy('created_at', 'desc');
        }


        public function scopePopular()

        {
            return $this->orderBy('view_count', 'desc');
        }


        public function scopePublished($query)

        {
            return $query->where("published_at", "<=", Carbon::now());
        }

        public function scopeScheduled($query)

        {
            return $query->where("published_at", ">", Carbon::now());
        }

        public function scopeDraft($query)

        {
            return $query->whereNull("published_at");
        }


        public function setPublishedAtAttribute($value)
        {
            $this->attributes['published_at'] = $value ?: NULL;
        }

        public function scopeFilter($query, $term)

        {
            if ($term){

                $query->where(function($q) use ($term){


                    $q->whereHas('author', function($qa) use ($term){

                        $qa->Where('name', 'LIKE', "%{$term}%");
                    });


                    $q->orWhereHas('category', function($qc) use ($term){

                        $qc->orWhere('title', 'LIKE', "%{$term}%");
                    });
                    
                $q->orWhere('title', 'LIKE', "%{$term}%");
                $q->orWhere('excerpt', 'LIKE', "%{$term}%");


                });

            }
        }

        public function tags(){

            return $this->belongsToMany(Tag::class);
        }


        public function createTags($str)
        {
            $tags = explode(",", $str);
            $tagIds = [];
    
            foreach ($tags as $tag)
            {
                $newTag = Tag::firstOrCreate([
                    'name' => ucwords(trim($tag))
                ]);
    
                $tagIds[] = $newTag->id;
            }
    
            $this->tags()->sync($tagIds);
        }

        public function getTagsHtmlAttribute()
        {
            $anchors = [];
            foreach($this->tags as $tag) {
                $anchors[] = '<a href="' . route('tag', $tag->name) . '">' . '</a>';
            }
            return implode(", ", $anchors);
        }


}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use GrahamCampbell\Markdown\Facades\Markdown;

class User extends Authenticatable
{
    use Notifiable;

/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [ 'name', 'email', 'password','bio', 'profile'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];



public function posts()
    {
        return $this->hasMany(Post::class , 'author_id');
    }

    public function getBioHtmlAttribute($value){

    return $this->bio ? Markdown::convertToHtml(e($this->bio)): NULL;
}

public function getProfileUrlAttribute($value){

    $profileUrl = "";

    if ( ! is_null($this->profile))

  {

    $profilePath = public_path(). '/avatar/'.$this->profile;
    if (file_exists($profilePath)) $profileUrl = asset('avatar/'. $this->profile);
  }

  return $profileUrl;
}


public function setPasswordAttribute($value)
{
    if (!empty($value)) $this->attributes['password'] = bcrypt($value);
}




}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;
use App\Category;
use App\Post;
use App\User;
use App\Tag;

class BlogController extends Controller
{

    protected $limit = 2;
    public function index()
    {
        $categories = Category::with('posts')->orderBy('title', 'asc')->get();

        $posts = Post::with('author')
                    ->latestFirst()
                    ->published()
                    ->filter(request('term'))
                     ->simplePaginate($this->limit);

        return view("blog.index", compact('posts', 'categories'));
    }

    public function about()
    {
        return view("blog.about.about");
    }

    public function contact()
    {
        return view("blog.contact.contact");
    }

    public function category($id)
    {
        $categories = Category::with('posts')->orderBy('title', 'asc')->get();

        $posts = Post::with('author')
                    ->latestFirst()
                    ->where('category_id', $id)
                    ->simplePaginate($this->limit);

         return view("blog.index", compact('posts'));

    }

    public function tag(Tag $id)
    {
        $tag = Post::with('tags')->orderBy('title', 'asc')->get();

        $posts = Post::with('author')
                    ->latestFirst()
                    ->published()
                    ->simplePaginate($this->limit);

         return view("blog.index", compact('posts'));

    }

    public function show(Post $post)

    {


        // upadte post with view count

        $post->increment('view_count');
        
        return view('blog.show', compact('post'));
    }

        
}

resources/views/blog/index.blade.php
@extends('layouts.main')

@section('content')


    <div class="container">
        <div class="row">
            <div class="col-md-8">

            @if (! $posts->count())

                <div class="alert alert-info"  padding= '10'>
                          <h1>No Post Found</p>

                </div>

            @elseif($term = request('term'))
            <div class="alert alert-info"  padding= '10'>
                          <p>Search Results for: <strong>{{ $term }}</strong></p>

                </div>

            @endif
             

                  @foreach($posts as $post)
                 
                <article class="post-item">

                @if ($post->image_url)

                    <div class="post-item-image">
                    <a href="{{route('blog.show', $post->id)}}">
                            <img src="{{$post->image_url}}" alt="">
                        </a>
                    </div>

                @endif

                    <div class="post-item-body">
                        <div class="padding-10">
                        <h2><a href="{{route('blog.show', $post->id)}}">{{$post->title}}</a></h2>
                            {!! $post->excerpt_html !!}
                        </div>

                        <div class="post-meta padding-10 clearfix">
                            <div class="pull-left">
                                <ul class="post-meta-group">
                                    <li><i class="fa fa-user"></i><a>{{$post->author->name}}</a></li>
                                    <li><i class="fa fa-clock-o"></i><time>{{$post->date}}</time></li>
                                    <li><i class="fa fa-folder"></i><a href="{{route('category', $post->category->id)}}">{{ $post->category->title}}</a></li>
                                    <li><i class="fa fa-tag"></i>{!!$post-> tags_html !!}</li>
                                </ul>
                            </div>
                            <div class="pull-right">
                                <a href="{{route('blog.show', $post->id)}}">Continue Reading &raquo;</a>
                            </div>
                        </div>
                    </div>
                </article>


                @endforeach


                <nav>
                        {{$posts->appends(request()->only(['term']))->links() }}
                </nav>
            </div>
            @include('layouts.sidebar')

            </div>
    </div>

@endsection

resources/views/blog/show.blade.php
@extends('layouts.main')

@section('content')


    <div class="container">
        <div class="row">
            <div class="col-md-8">

        
                <article class="post-item">


                                @if ($post->image_url)
                                    <div class="post-item-image">
                                            <a href="">
                                                <img src="{{$post->image_url}}" alt="{{$post-> title }}">
                                            </a>
                                    </div>

                                @endif

                            <div class="post-item-body">

                                        <div class="padding-10">

                                        <h1>{{$post->title}}</h1>
                                            
                                        </div>

                            
                                    <div class="post-meta no-broder">
                                        <ul class="post-meta-group">
                                            <li><i class="fa fa-user"></i><a>{{$post-> author->name}}</a></li>
                                            <li><i class="fa fa-clock-o"></i><time>{{$post->date}}</time></li>
                                            <li><i class="fa fa-folder"></i><a href="{{route('category', $post->category->id)}}">{{ $post->category->title}}</a></li>
                                            <li><i class="fa fa-tag"></i>{!!$post-> tags_html !!}</li>
                                        </ul>
                                    </div>

                                    <div class="post-item-body">

                                        <div class="padding-10">
                                        
                                            {!!$post->body_html !!}
                                            
                                        </div>
                                    </div>      
                            </div>
                </article>

                <article class="post-author padding-10">
                    <div class="media">
                            <div class="media-left">
                            
                                <a>
                                <img alt="{{ $post->author->name }}" width="100" height="100" src="{{ $post->author->profile_url }}" class="media-object">
                                </a>
                            </div>


                            <div class="media-body">
                                <h4 class="media-heading"><a>{{ $post->author->name }}</a></h4>
                                            <div class='post-author-count'>
                                            <p><a><i class="fa fa-clone"></i>
                                                    {{$post->author->posts->count()}}
                                                </a>posts </p>
                                            </div>
                                      
                                            <div>
                                            
                                                {!! $post->author->bio_html !!}
                                            </div>

                            </div>
                    
                    </div>
                </article>


            </div>


            @include('layouts.sidebar')

            </div>
    </div>

@endsection